FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install git -y
RUN apt install software-properties-common -y
RUN apt-add-repository --yes --update ppa:ansible/ansible -y
RUN apt install ansible -y
RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
CMD echo 'StrictHostKeyChecking no' >>  /etc/ssh/ssh_config
RUN sed -i -e "s/#host_key_checking = False/host_key_checking = False/g" /etc/ansible/ansible.cfg
RUN apt-get clean